#Console
server:
  port: 8080 # ?? ??(???? 8080)
spring:
  output:
    ansi:
      enabled: always
  profiles:
    active: dev # ????? dev ???? ??
  thymeleaf:
    cache: false # ???? ?? ??
    prefix: file:src/main/resources/templates/ # ???? ?? ??(? ??? ?? ??)
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/sbb__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update # DB ??? ????(??? ???? ??? ?)
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
            extract: trace
